version: '3.1'
services:
    mariadb:
        image: mariadb:latest
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: 1234
        volumes:
            - ./mariadb/:/var/lib/mysql:Z
        restart: unless-stopped
    redis:
        image: redis
